version: "3"
services:
  anim-backend:
    container_name: todo-list-api-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      ENV_NAME: production
    ports:
      - 9999:9999
